import { createApp } from 'vue'
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import NotifyPlugin from 'vue-easy-notify'
import store from './vuex'
import './axios'
import 'vue-easy-notify/dist/vue-easy-notify.css'
import '@/assets/css/style.css'
import '@/assets/css/bootstrap.min.css'
import '@/assets/js/bootstrap.min.js'
import '@/assets/themify-icons/themify-icons.css'
import '@/assets/css/metisMenu.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import '@fortawesome/fontawesome-free/css/all.css'
import '@fortawesome/fontawesome-free/js/all.js'
import AOS from 'aos'
import 'aos/dist/aos.css'
import $ from 'jquery'

createApp(App).use(router).use(store).use(AOS.init()).mount('#app')